# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exitaccept.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_exitaccept(object):
    def setupUi(self, exitaccept):
        exitaccept.setObjectName("exitaccept")
        exitaccept.resize(400, 163)
        exitaccept.setWindowOpacity(2.5)
        exitaccept.setStyleSheet("QDialog\n"
"{\n"
"background:#333;\n"
"border-radius:15px;\n"
"}\n"
"\n"
"\n"
"\n"
"QLabel\n"
"{\n"
"font-family: century gothic;\n"
"font-size:24px;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"background: steelblue;\n"
"border-radius: 10px;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"background: teal;\n"
"border-radius: 10px;\n"
"color: white;\n"
"}")
        self.pushButton_4 = QtWidgets.QPushButton(exitaccept)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 60, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(exitaccept)
        self.pushButton_5.setGeometry(QtCore.QRect(230, 60, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("*{\n"
"background-color:red;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"background: darkred;\n"
"border-radius:15px;\n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_5 = QtWidgets.QLabel(exitaccept)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 391, 41))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")

        self.retranslateUi(exitaccept)
        QtCore.QMetaObject.connectSlotsByName(exitaccept)

    def retranslateUi(self, exitaccept):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton_4.setText(_translate("exitaccept", "ДА"))
        self.pushButton_5.setText(_translate("exitaccept", "НЕТ"))
        self.label_5.setText(_translate("exitaccept", "Вы действительно хотите выйти?"))
