# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'howreg.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_howreg(object):
    def setupUi(self, howreg):
        howreg.setObjectName("howreg")
        howreg.resize(400, 163)
        howreg.setMinimumSize(QtCore.QSize(400, 0))
        howreg.setWindowTitle("")
        howreg.setStyleSheet("QDialog\n"
"{\n"
"background:#333;\n"
"border-radius:15px;\n"
"}\n"
"\n"
"\n"
"\n"
"QLabel\n"
"{\n"
"font-family: century gothic;\n"
"font-size:24px;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"background: steelblue;\n"
"border-radius: 10px;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"background: teal;\n"
"border-radius: 10px;\n"
"color: white;\n"
"}")
        self.pushButton_4 = QtWidgets.QPushButton(howreg)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 60, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_5 = QtWidgets.QLabel(howreg)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 391, 41))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.pushButton_5 = QtWidgets.QPushButton(howreg)
        self.pushButton_5.setGeometry(QtCore.QRect(230, 60, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_2 = QtWidgets.QPushButton(howreg)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 130, 121, 27))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton\n"
"{\n"
"background-color: red;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"background-color: darkred;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(howreg)
        QtCore.QMetaObject.connectSlotsByName(howreg)

    def retranslateUi(self, howreg):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton_4.setText(_translate("howreg", "Участника"))
        self.label_5.setText(_translate("howreg", "Зарегистрироваться в качестве"))
        self.pushButton_5.setText(_translate("howreg", "Эксперта"))
        self.pushButton_2.setText(_translate("howreg", "Назад"))
